services:
  dungap:
    build:
      target: production
    environment:
      PWA_UPSTREAM: localhost:3000
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      API_ENTRYPOINT: "http://localhost"
