# Development environment override
services:
  dungap:
    build:
      target: dev
    volumes:
      - ./api:/srv/api
      - /srv/api/var
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./pwa:/srv/pwa
      - ./vars/log:/var/log/dungap
      # - /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - 5173:5173
