services:
  dungap:
    container_name: dungap
    image: ${IMAGES_PREFIX:-dungap}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      DUNGAP_SERVER_NAME: ${DUNGAP_SERVER_NAME:-localhost}
      DUNGAP_URL: ${DUNGAP_URL:-localhost}
      DUNGAP_SECRET: ${DUNGAP_SECRET:-!changeme!}
      DUNGAP_JWT_SECRET: ${DUNGAP_JWT_SECRET:-!changeme!}
      DUNGAP_PWA_UPSTREAM: ${DUNGAP_PWA_UPSTREAM:-localhost:5173}
      DUNGAP_API_ENTRYPOINT: ${DUNGAP_API_ENTRYPOINT:-https://localhost}
      DUNGAP_DATABASE_DSN: ${DUNGAP_DATABASE_DSN:-sqlite:///%kernel.project_dir%/var/data.db}
    cap_add:
      - ALL
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
