services:
  api:
    container_name: dungap-api
    image: ${IMAGES_PREFIX:-dungap}-api
    restart: unless-stopped
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost}, api:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|api$$
      #DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@${POSTGRES_HOST:-database}:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://api/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      OIDC_UPSTREAM: https://localhost/change/me
      OIDC_SERVER_URL: ${OIDC_SERVER_URL:-https://localhost/oidc/realms/demo}
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  pwa:
    container_name: dungap-pwa
    image: ${IMAGES_PREFIX:-dungap}-pwa
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://api
      NEXT_SHARP_PATH: /srv/app/node_modules/sharp
      AUTH_SECRET: ${AUTH_SECRET:-!ChangeThisNextAuthSecret!}
      AUTH_URL: ${AUTH_URL:-https://localhost/api/auth}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-dungap-pwa}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:-dungap-api}
      OIDC_ISSUER: ${OIDC_ISSUER:-https://localhost/oidc/realms/demo}

volumes:
  caddy_data:
  caddy_config:
