---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task -l

  build:*:
    cmds:
      - docker build --target {{.target}} -f docker/Dockerfile -t dungap:{{.target}} .
    vars:
      target: "{{index .MATCH 0}}"

  up:
    cmd: docker compose up -d

  up:prod:
    cmd: docker compose -f compose.yaml -f compose.prod.yaml up -d

  stop:
    cmd: docker compose stop

  start:
    cmd: docker compose start

  restart:
    cmds:
      - task: stop
      - task: start

  logs:
    cmd: docker compose logs -f --tail 50

  logs:franken:
    cmd: docker compose exec dungap tail -f /var/log/caddy.log

  logs:pwa:
    cmd: docker compose exec dungap tail -f /var/log/pwa.log

  rm:
    cmds:
      - task: stop
      - docker compose rm -f

  shell:
    cmds:
      - docker compose exec dungap bash

  sf:cc:
    cmds:
      - task: .sf
        vars:
          CLI_ARGS: "cache:clear {{.CLI_ARGS}}"

  sf:
    cmds:
      - task: .sf

  .sf:
    cmd: docker compose exec dungap /srv/api/bin/console {{.CLI_ARGS}}
