core:
  config_dirs: /config
node:
  default_processor:
    power_on: etherwake
    power_off: ssh
    reboot: ssh
  hosts: []
service:
  scanner:
    - port: 22
doctrine:
  orm:
    mappings:
      Node:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Node/Entity"
        prefix: 'Dungap\Node\Entity'
        alias: Node
      State:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/State/Entity"
        prefix: 'Dungap\State\Entity'
        alias: State
      Service:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Service/Entity"
        prefix: 'Dungap\Service\Entity'
        alias: Service
      User:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/User/Entity"
        prefix: 'Dungap\User\Entity'
        alias: User
    resolve_target_entities:
      Dungap\Contracts\Node\NodeInterface: Dungap\Node\Entity\Node
      Dungap\Contracts\Node\AttributeInterface: Dungap\Node\Entity\Attribute
      Dungap\Contracts\State\StateInterface: Dungap\State\Entity\State
      Dungap\Contracts\Service\ServiceInterface: Dungap\Service\Entity\Service
      Dungap\Contracts\User\UserInterface: Dungap\User\Entity\User
      Dungap\Contracts\Attribute\MetaInterface: Dungap\Attribute\Entity\Meta

api_platform:
  use_symfony_listeners: true
  resource_class_directories:
    - "%kernel.project_dir%/src/Node/Entity"
    - "%kernel.project_dir%/src/State/Entity"
    - "%kernel.project_dir%/src/Service/Entity"
  mercure:
    include_type: true

lexik_jwt_authentication:
  secret_key: '%env(resolve:DUNGAP_SECURITY_JWT_SECRET_KEY)%'
  public_key: '%env(resolve:DUNGAP_SECURITY_JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(DUNGAP_SECURITY_JWT_PASSPHRASE)%'
  api_platform:
    check_path: /api/jwt-check
    username_path: email
    password_path: security.credentials.password

when@dev: &dev
  core:
    config_dirs: "../tests/fixtures/config"

when@test: *dev
