core:
  config_dirs: /config
node:
  hosts: []

doctrine:
  orm:
    mappings:
      Node:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/Node/Entity"
        prefix: 'Dungap\Node\Entity'
        alias: Node
      State:
        type: attribute
        is_bundle: false
        dir: "%kernel.project_dir%/src/State/Entity"
        prefix: 'Dungap\State\Entity'
        alias: State
    resolve_target_entities:
      Dungap\Contracts\Node\NodeInterface: Dungap\Node\Entity\Node
      Dungap\Contracts\State\StateInterface: Dungap\State\Entity\State

api_platform:
  resource_class_directories:
    - "%kernel.project_dir%/src/Node/Entity"
    - "%kernel.project_dir%/src/State/Entity"
  mercure:
    include_type: true

when@dev: &dev
  core:
    config_dirs: "../tests/fixtures/config"

when@test: *dev
