mercure:
  hubs:
    default:
      url: '%env(DUNGAP_URL)%/.well-known/mercure'
      public_url: '%env(DUNGAP_URL)%/.well-known/mercure'
      jwt:
        secret: '%env(DUNGAP_JWT_SECRET)%'
        publish: '*'
