security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "bcrypt"
  providers:
    username_email:
      id: 'Dungap\Security\Provider\UsernameEmailProvider'
    attributes:
      id: 'Dungap\Security\Provider\AttributesUserProvider'
    #users:
    #  chain:
    #    providers: ["username_email", "attributes"]
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: attributes
      stateless: true
  access_control:
    - { path: ^/admin, roles: IS_AUTHENTICATED }

when@prod: &prod
  security:
    firewalls:
      main:
        access_token:
          token_handler: Dungap\Security\Core\OidcTokenHandler

when@dev: *prod
