framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    Dungap\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
