---
file:
  /usr/local/bin/php:
    exists: true
  /usr/local/bin/composer:
    exists: true
  /srv/api/bin/console:
    exists: true
  /srv/pwa:
    exists: true
  /srv/pwa/build:
    exists: true
  /srv/pwa/public:
    exists: true
  /srv/pwa/node_modules:
    exists: true
  /usr/local/bin/api-entrypoint:
    exists: true
  /usr/local/bin/dungap-entrypoint:
    exists: true

http:
  pwa:
    url: https://localhost/dashboard
    status: 200
    allow-insecure: true
    timeout: 5000
    method: GET
    request-headers:
      - "Accept: text/html"
    headers:
      - "Content-Type: text/html"
  api:
    url: https://localhost/nodes
    status: 200
    allow-insecure: true
    timeout: 5000
    method: GET
    headers:
      - "Content-Type: application/ld+json"

port:
  metrics:
    listening: true
    port: "tcp:2019"
  https:
    listening: true
    port: "tcp6:443"
  mercure:
    listening: true
    port: "udp6:443"
  pwa:
    listening: true
    port: "tcp6:3000"
