name: Build Images

on:
  workflow_dispatch:
    inputs:
      pushImages:
        required: false
        default: "false"
        type: string
  workflow_call:
    inputs:
      pushImages:
        required: false
        default: "false"
        type: string

env:
  IMAGE_PREFIX: ghcr.io/kilip/dungap

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build tags
        id: tag
        run: |
          date_tag=$(date +'%Y%m%d%H%M%S')
          API_IMAGE=${IMAGE_PREFIX}-api
          PWA_IMAGE=${IMAGE_PREFIX}-pwa

          echo "API_DATE=${API_IMAGE}:main-${date_tag}" >> "$GITHUB_OUTPUT"

      - name: Setup Goss
        uses: e1himself/goss-installation-action@v1.2.1
        with:
          version: v0.3.21

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image for testing
        uses: docker/build-push-action@v5
        with:
          target: production
          context: .
          platforms: linux/amd64 # load does not support muti-arch https://github.com/docker/buildx/issues/290
          load: true
          tags: ${IMAGE_PREFIX}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Goss tests
        id: dgoss
        shell: bash
        env:
          CONTAINER_RUNTIME: docker
          GOSS_FILE: ./docker/goss.yaml
          GOSS_OPTS: --retry-timeout 60s --sleep 2s --color --format documentation
          GOSS_SLEEP: 2
          GOSS_FILES_STRATEGY: cp
          CONTAINER_LOG_OUTPUT: goss_container_log_output
        run: dgoss run ${IMAGE_PREFIX}:test
