---
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  api:
    name: API Test
    uses: kilip/dungap/.github/workflows/api.yaml@main
    secrets: inherit

  pwa:
    name: PWA Test
    uses: kilip/dungap/.github/workflows/pwa.yaml@main
    secrets: inherit

  e2e:
    name: E2E Testing
    uses: kilip/dungap/.github/workflows/e2e.yaml@main
    needs: [api, pwa]
    secrets: inherit
    if: >
      needs.api.result != 'failure'
      && needs.pwa.result != 'failure'

  deploy:
    name: Deploy
    uses: kilip/dungap/.github/workflows/deploy.yaml@main
    needs: [e2e]
    secrets: inherit
    if: >
      needs.e2e.result != 'failure'
      && github.event_name != 'pull_request'
    with:
      pushImages: "true"

  release:
    name: Create Release
    uses: kilip/dungap/.github/workflows/release.yaml@main
    needs: [e2e]
    secrets: inherit
    if: >
      needs.e2e.result != 'failure'
      && github.event_name != 'pull_request'
      && github.ref_name != 'main'
