---
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  api:
    name: API Test
    uses: kilip/dungap/.github/workflows/api.yaml@main
    secrets: inherit
