name: Deploy

on:
  workflow_dispatch:
    inputs:
      pushImages:
        required: false
        default: "false"
        type: string
  workflow_call:
    inputs:
      pushImages:
        required: false
        default: "false"
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Tags
        id: vars
        uses: ./.github/actions/build-tags

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container images
        uses: docker/build-push-action@v6
        with:
          target: production
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          load: false
          tags: |
            ${{ steps.vars.outputs.rolling }}
            ${{ steps.vars.outputs.version }}
          push: ${{ inputs.pushImages == 'true' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./docker/Dockerfile
